In [103]:
import polars as pl
from polars import col
import numpy as np
import torch
import time

In [18]:
torch.get_default_device()

device(type='cpu')

In [86]:
torch.set_default_device('cuda')

In [87]:
torch.get_default_device()

device(type='cuda', index=0)

In [2]:
df=pl.read_csv('/home/fjc/Documents/data/202302/000001.csv')
df

shape: (4_820, 9)
┌──────┬─────────────────────┬───────┬───────┬───┬───────┬─────────┬───────────┬────────┐
│ code ┆ tdate               ┆ open  ┆ close ┆ … ┆ low   ┆ cjl     ┆ cje       ┆ cjjj   │
│ ---  ┆ ---                 ┆ ---   ┆ ---   ┆   ┆ ---   ┆ ---     ┆ ---       ┆ ---    │
│ i64  ┆ str                 ┆ f64   ┆ f64   ┆   ┆ f64   ┆ f64     ┆ f64       ┆ f64    │
╞══════╪═════════════════════╪═══════╪═══════╪═══╪═══════╪═════════╪═══════════╪════════╡
│ 1    ┆ 2023-02-01 09:30:00 ┆ 15.03 ┆ 15.03 ┆ … ┆ 15.03 ┆ 3601.0  ┆ 5.4123e6  ┆ 15.03  │
│ 1    ┆ 2023-02-01 09:31:00 ┆ 15.03 ┆ 14.97 ┆ … ┆ 14.95 ┆ 19919.0 ┆ 2.98901e7 ┆ 15.01  │
│ 1    ┆ 2023-02-01 09:32:00 ┆ 14.97 ┆ 15.03 ┆ … ┆ 14.97 ┆ 7600.0  ┆ 1.14196e7 ┆ 15.014 │
│ 1    ┆ 2023-02-01 09:33:00 ┆ 15.03 ┆ 15.02 ┆ … ┆ 15.0  ┆ 3767.0  ┆ 5.65412e6 ┆ 15.013 │
│ 1    ┆ 2023-02-01 09:34:00 ┆ 15.01 ┆ 15.01 ┆ … ┆ 15.0  ┆ 5175.0  ┆ 7.76705e6 ┆ 15.013 │
│ …    ┆ …                   ┆ …     ┆ …     ┆ … ┆ …     ┆ …       ┆ …         ┆ …      │
│ 1    ┆ 2023-02-28 14:56:00 ┆ 13.78 ┆ 13.79 ┆ … ┆ 13.77 ┆ 3833.0  ┆ 5.28268e6 ┆ 13.704 │
│ 1    ┆ 2023-02-28 14:57:00 ┆ 13.78 ┆ 13.79 ┆ … ┆ 13.78 ┆ 6322.0  ┆ 8.71505e6 ┆ 13.704 │
│ 1    ┆ 2023-02-28 14:58:00 ┆ 13.79 ┆ 13.79 ┆ … ┆ 13.79 ┆ 812.0   ┆ 1.11974e6 ┆ 13.705 │
│ 1    ┆ 2023-02-28 14:59:00 ┆ 13.79 ┆ 13.79 ┆ … ┆ 13.79 ┆ 0.0     ┆ 0.0       ┆ 13.705 │
│ 1    ┆ 2023-02-28 15:00:00 ┆ 13.78 ┆ 13.78 ┆ … ┆ 13.78 ┆ 22772.0 ┆ 3.138e7   ┆ 13.707 │
└──────┴─────────────────────┴───────┴───────┴───┴───────┴─────────┴───────────┴────────┘

In [64]:
sample=df.with_columns(pl.col('open').shift(-2).alias('label')).with_columns([
    ((pl.col(col) - pl.col(col).mean()) / pl.col(col).std()).alias(f"{col}_standardized")
    for col in ['open',	'close',	'high',	'low',	'cjl',	'cje',	'cjjj']
])
sample

shape: (4_820, 17)
┌──────┬──────────────┬───────┬───────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ code ┆ tdate        ┆ open  ┆ close ┆ … ┆ low_standard ┆ cjl_standar ┆ cje_standar ┆ cjjj_standa │
│ ---  ┆ ---          ┆ ---   ┆ ---   ┆   ┆ ized         ┆ dized       ┆ dized       ┆ rdized      │
│ i64  ┆ str          ┆ f64   ┆ f64   ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│      ┆              ┆       ┆       ┆   ┆ f64          ┆ f64         ┆ f64         ┆ f64         │
╞══════╪══════════════╪═══════╪═══════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 1    ┆ 2023-02-01   ┆ 15.03 ┆ 15.03 ┆ … ┆ 3.775712     ┆ -0.180804   ┆ -0.128228   ┆ 3.661964    │
│      ┆ 09:30:00     ┆       ┆       ┆   ┆              ┆             ┆             ┆             │
│ 1    ┆ 2023-02-01   ┆ 15.03 ┆ 14.97 ┆ … ┆ 3.485871     ┆ 3.102903    ┆ 3.374274    ┆ 3.590286    │
│      ┆ 09:31:00     ┆       ┆       ┆   ┆              ┆             ┆             ┆             │
│ 1    ┆ 2023-02-01   ┆ 14.97 ┆ 15.03 ┆ … ┆ 3.558332     ┆ 0.623924    ┆ 0.73135     ┆ 3.604622    │
│      ┆ 09:32:00     ┆       ┆       ┆   ┆              ┆             ┆             ┆             │
│ 1    ┆ 2023-02-01   ┆ 15.03 ┆ 15.02 ┆ … ┆ 3.667022     ┆ -0.147399   ┆ -0.093627   ┆ 3.601038    │
│      ┆ 09:33:00     ┆       ┆       ┆   ┆              ┆             ┆             ┆             │
│ 1    ┆ 2023-02-01   ┆ 15.01 ┆ 15.01 ┆ … ┆ 3.667022     ┆ 0.135936    ┆ 0.20871     ┆ 3.601038    │
│      ┆ 09:34:00     ┆       ┆       ┆   ┆              ┆             ┆             ┆             │
│ …    ┆ …            ┆ …     ┆ …     ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ 1    ┆ 2023-02-28   ┆ 13.78 ┆ 13.79 ┆ … ┆ -0.789283    ┆ -0.134118   ┆ -0.146776   ┆ -1.090273   │
│      ┆ 14:56:00     ┆       ┆       ┆   ┆              ┆             ┆             ┆             │
│ 1    ┆ 2023-02-28   ┆ 13.78 ┆ 13.79 ┆ … ┆ -0.753053    ┆ 0.366749    ┆ 0.344358    ┆ -1.090273   │
│      ┆ 14:57:00     ┆       ┆       ┆   ┆              ┆             ┆             ┆             │
│ 1    ┆ 2023-02-28   ┆ 13.79 ┆ 13.79 ┆ … ┆ -0.716823    ┆ -0.74204    ┆ -0.742446   ┆ -1.086689   │
│      ┆ 14:58:00     ┆       ┆       ┆   ┆              ┆             ┆             ┆             │
│ 1    ┆ 2023-02-28   ┆ 13.79 ┆ 13.79 ┆ … ┆ -0.716823    ┆ -0.905441   ┆ -0.902669   ┆ -1.086689   │
│      ┆ 14:59:00     ┆       ┆       ┆   ┆              ┆             ┆             ┆             │
│ 1    ┆ 2023-02-28   ┆ 13.78 ┆ 13.78 ┆ … ┆ -0.753053    ┆ 3.677018    ┆ 3.587462    ┆ -1.079521   │
│      ┆ 15:00:00     ┆       ┆       ┆   ┆              ┆             ┆             ┆             │
└──────┴──────────────┴───────┴───────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [65]:
train_data=sample.filter(col('tdate') <= "2023-02-26 15:00:00").select('open_standardized',	'close_standardized',	'high_standardized',	
                                                                       'low_standardized',	'cjl_standardized',	'cje_standardized',
                                                                       'cjjj_standardized','label')
train_X=train_data.drop('label')
train_y=train_data['label']

predict_data=sample.filter(col('tdate') > "2023-02-26 15:00:00").select('open_standardized',	'close_standardized',	'high_standardized',	
                                                                       'low_standardized',	'cjl_standardized',	'cje_standardized',
                                                                       'cjjj_standardized','label')
predict_X=predict_data.drop('label')
predict_y=predict_data['label']

In [88]:
X=train_X.to_torch(dtype=pl.Float32).to('cuda:0', dtype=torch.float)
y=train_y.to_torch().to('cuda:0', dtype=torch.float)
X,y

(tensor([[ 3.7228,  3.7320,  3.6782,  ..., -0.1808, -0.1282,  3.6620],
         [ 3.7228,  3.5152,  3.8579,  ...,  3.1029,  3.3743,  3.5903],
         [ 3.5065,  3.7320,  3.7501,  ...,  0.6239,  0.7313,  3.6046],
         ...,
         [-0.4236, -0.4238, -0.4547,  ..., -0.9004, -0.8977, -0.4882],
         [-0.4236, -0.4238, -0.4547,  ..., -0.9054, -0.9027, -0.4882],
         [-0.4957, -0.4961, -0.5266,  ...,  0.6263,  0.6070, -0.4882]],
        device='cuda:0'),
 tensor([14.9700, 15.0300, 15.0100,  ..., 13.8600, 13.7500, 13.7400],
        device='cuda:0'))

In [77]:
X.dtype

torch.float32

In [89]:
X.device

device(type='cuda', index=0)

# 1. 自行管理迭代和loss
## cpu cost: 48.45271134376526s
## gpu cost: 1.5118281841278076s

In [90]:
# 权重参数初始化.每一层的神经元个数及初始权重.此处共三层
weights = torch.randn((7, 128), dtype = torch.float, requires_grad = True) # 第一层输入7个特征向量(神经元),输出128个特征向量,对应下一层
biases = torch.randn(128, dtype = torch.float, requires_grad = True) 

weights2 = torch.randn((128, 64), dtype = torch.float, requires_grad = True)  #第二层输入128个特征向量(神经元),输出64个特征向量,对应下一层
biases2 = torch.randn(64, dtype = torch.float, requires_grad = True) 

weights3 = torch.randn((64, 1), dtype = torch.float, requires_grad = True) #第二层输入64个特征向量(神经元),输出1个预测值
biases3 = torch.randn(1, dtype = torch.float, requires_grad = True) 

learning_rate = 0.0001  
# 学习率要设得很小,否则梯度爆炸
# relu激活函数允许输出无限大,会导致loss无限大,可以减小学习率,数据归一化等解决,也可以通过梯度裁剪, 切换优化器, 切换激活函数等解决
losses = []

start=time.time()
for i in range(1000):
    # 计算隐层
    hidden = X.mm(weights) + biases
    # 加入激活函数
    hidden = torch.relu(hidden)
    #第二个隐藏层
    hidden = hidden.mm(weights2) + biases2
    hidden = torch.relu(hidden)
    
    # 预测结果
    predictions = hidden.mm(weights3) + biases3
    # 通计算损失
    loss = torch.mean((predictions - y) ** 2) 
    # losses.append(loss.cpu().data.numpy())
    # 打印损失值
    if i % 100 == 0:
        print('loss:', loss)
    #返向传播计算
    loss.backward()  #只计算梯度,不更新参数
    
    #更新参数
    weights.data.add_(- learning_rate * weights.grad.data)  
    biases.data.add_(- learning_rate * biases.grad.data)
    weights2.data.add_(- learning_rate * weights2.grad.data)
    biases2.data.add_(- learning_rate * biases2.grad.data)

    weights3.data.add_(- learning_rate * weights3.grad.data)
    biases3.data.add_(- learning_rate * biases3.grad.data)
    
    # 每次迭代都得记得清空,不然下一次更新参数会使用累计梯度
    weights.grad.data.zero_()
    biases.grad.data.zero_()
    weights2.grad.data.zero_()
    biases2.grad.data.zero_()
    weights3.grad.data.zero_()
    biases3.grad.data.zero_()
end=time.time()
print(f"gpu cost: {end-start}s")

loss: tensor(14337.9668, device='cuda:0', grad_fn=<MeanBackward0>)
loss: tensor(13.0314, device='cuda:0', grad_fn=<MeanBackward0>)
loss: tensor(7.8389, device='cuda:0', grad_fn=<MeanBackward0>)
loss: tensor(5.8750, device='cuda:0', grad_fn=<MeanBackward0>)
loss: tensor(4.7990, device='cuda:0', grad_fn=<MeanBackward0>)
loss: tensor(4.0892, device='cuda:0', grad_fn=<MeanBackward0>)
loss: tensor(3.5702, device='cuda:0', grad_fn=<MeanBackward0>)
loss: tensor(3.1696, device='cuda:0', grad_fn=<MeanBackward0>)
loss: tensor(2.8503, device='cuda:0', grad_fn=<MeanBackward0>)
loss: tensor(2.5914, device='cuda:0', grad_fn=<MeanBackward0>)
gpu cost: 1.5118281841278076s

In [85]:
predictions

tensor([[12.8494],
        [16.5160],
        [17.0770],
        ...,
        [17.3530],
        [17.3295],
        [ 9.0494]], grad_fn=<AddBackward0>)

# 2. 调用torch方法管理网络

In [123]:
input_size = X.shape[1]  #特征数
hidden_size = 128
output_size = 1
batch_size = 256
my_nn = torch.nn.Sequential(
    torch.nn.Linear(input_size, hidden_size),  #输入层
    torch.nn.ReLU(),   # 激活函数
    torch.nn.Linear(hidden_size, output_size), #输出层
)
cost = torch.nn.MSELoss(reduction='mean')  #loss函数
optimizer = torch.optim.Adam(my_nn.parameters(), lr = 0.0001)  #优化器,管理参数更新.可以动态调整学习率,初始较大,然后慢慢变小

In [135]:
# 训练网络
losses = []
for i in range(1000):
    batch_loss = []
    # MINI-Batch方法来进行训练
    for start in range(0, train_X.height, batch_size):
        xx = train_X.slice(start,batch_size).to_torch(dtype=pl.Float32).to('cuda:0', dtype=torch.float)
        yy = train_y.slice(start,batch_size).to_torch().to('cuda:0', dtype=torch.float)
        prediction = my_nn(xx)
        
        loss = cost(prediction.squeeze(), yy)  #prediction输出是(n,1)tensor,需要去除数量为1的维度才能计算loss
        
        optimizer.zero_grad()
        
        loss.backward(retain_graph=True)
        
        optimizer.step()  # 更新参数
        # has_nan = torch.isnan(loss).any()
        # if has_nan:
        #     print(start,batch_size)
        
        batch_loss.append(loss.cpu().data.numpy())
    
    # 打印损失
    if i % 100==0:
        losses.append(np.mean(batch_loss))
        print(i, np.mean(batch_loss))

0 2.835486
100 0.5493558
200 0.07182373
300 0.024019893
400 0.010280422
500 0.004933674
600 0.0031746952
700 0.0032718661
800 0.0027922988
900 0.0024141686

# 预测

In [140]:
predict_tensor = predict_X.to_torch(dtype=pl.Float32).to('cuda:0', dtype=torch.float)
predict = my_nn(predict_tensor).cpu().data.numpy()
predict

array([[13.70953  ],
       [13.783541 ],
       [13.746778 ],
       [13.792823 ],
       [13.7748375],
       [13.750422 ],
       [13.782487 ],
       [13.786427 ],
       [13.791538 ],
       [13.771093 ],
       [13.744836 ],
       [13.757482 ],
       [13.727609 ],
       [13.791236 ],
       [13.787109 ],
       [13.832314 ],
       [13.9065895],
       [13.891856 ],
       [13.841562 ],
       [13.861987 ],
       [13.84472  ],
       [13.92834  ],
       [13.886503 ],
       [13.849197 ],
       [13.876596 ],
       [13.859316 ],
       [13.847126 ],
       [13.85324  ],
       [13.89262  ],
       [13.8511715],
       [13.815617 ],
       [13.794016 ],
       [13.780734 ],
       [13.788962 ],
       [13.786435 ],
       [13.720757 ],
       [13.785664 ],
       [13.8346   ],
       [13.797347 ],
       [13.773494 ],
       [13.802156 ],
       [13.838248 ],
       [13.784607 ],
       [13.794911 ],
       [13.795435 ],
       [13.816881 ],
       [13.78294  ],
       [13.7450075],
       [13.822173 ],
       [13.821877 ],
       [13.884521 ],
       [13.809985 ],
       [13.798052 ],
       [13.867786 ],
       [13.889367 ],
       [13.814026 ],
       [13.789372 ],
       [13.825021 ],
       [13.844374 ],
       [13.79351  ],
       [13.834625 ],
       [13.819352 ],
       [13.8214655],
       [13.818714 ],
       [13.839263 ],
       [13.853374 ],
       [13.850743 ],
       [13.83373  ],
       [13.827311 ],
       [13.816219 ],
       [13.80606  ],
       [13.828198 ],
       [13.83932  ],
       [13.837927 ],
       [13.844454 ],
       [13.8136015],
       [13.822453 ],
       [13.8116455],
       [13.799831 ],
       [13.832586 ],
       [13.802925 ],
       [13.801642 ],
       [13.834435 ],
       [13.849552 ],
       [13.839843 ],
       [13.874902 ],
       [13.855916 ],
       [13.876844 ],
       [13.830986 ],
       [13.862025 ],
       [13.858957 ],
       [13.840875 ],
       [13.855421 ],
       [13.870783 ],
       [13.868728 ],
       [13.852532 ],
       [13.873483 ],
       [13.836558 ],
       [13.834208 ],
       [13.826592 ],
       [13.849426 ],
       [13.871825 ],
       [13.867594 ],
       [13.833604 ],
       [13.833737 ],
       [13.832199 ],
       [13.854973 ],
       [13.842827 ],
       [13.85449  ],
       [13.828162 ],
       [13.784244 ],
       [13.818632 ],
       [13.856894 ],
       [13.821585 ],
       [13.818055 ],
       [13.842977 ],
       [13.801054 ],
       [13.754338 ],
       [13.730052 ],
       [13.746362 ],
       [13.809389 ],
       [13.745567 ],
       [13.806427 ],
       [13.817363 ],
       [13.8778105],
       [13.8744755],
       [13.895996 ],
       [13.876413 ],
       [13.849463 ],
       [13.877889 ],
       [13.829731 ],
       [13.864087 ],
       [13.883855 ],
       [13.851016 ],
       [13.863414 ],
       [13.845561 ],
       [13.828733 ],
       [13.806892 ],
       [13.777598 ],
       [13.732918 ],
       [13.832755 ],
       [13.756919 ],
       [13.755714 ],
       [13.787321 ],
       [13.761589 ],
       [13.75172  ],
       [13.803358 ],
       [13.809683 ],
       [13.76851  ],
       [13.719297 ],
       [13.752146 ],
       [13.801821 ],
       [13.740728 ],
       [13.800711 ],
       [13.707618 ],
       [13.713802 ],
       [13.789292 ],
       [13.723703 ],
       [13.700769 ],
       [13.748741 ],
       [13.759152 ],
       [13.753279 ],
       [13.676728 ],
       [13.674021 ],
       [13.667118 ],
       [13.672289 ],
       [13.668588 ],
       [13.69735  ],
       [13.6777525],
       [13.652713 ],
       [13.679353 ],
       [13.644773 ],
       [13.65924  ],
       [13.654388 ],
       [13.650797 ],
       [13.68125  ],
       [13.7009325],
       [13.66112  ],
       [13.656367 ],
       [13.669808 ],
       [13.7042265],
       [13.665815 ],
       [13.682075 ],
       [13.66441  ],
       [13.659949 ],
       [13.696434 ],
       [13.695199 ],
       [13.643577 ],
       [13.677221 ],
       [13.688602 ],
       [13.662495 ],
       [13.684686 ],
       [13.698671 ],
       [13.74175  ],
       [13.7005415],
       [13.704038 ],
       [13.713612 ],
       [13.69737  ],
       [13.692464 ],
       [13.666887 ],
       [13.6637335],
       [13.649555 ],
       [13.638924 ],
       [13.68023  ],
       [13.649744 ],
       [13.668715 ],
       [13.631917 ],
       [13.690334 ],
       [13.679738 ],
       [13.672579 ],
       [13.63924  ],
       [13.633292 ],
       [13.663339 ],
       [13.686893 ],
       [13.6316395],
       [13.663017 ],
       [13.666465 ],
       [13.670925 ],
       [13.692084 ],
       [13.632374 ],
       [13.650833 ],
       [13.648993 ],
       [13.694897 ],
       [13.692388 ],
       [13.672981 ],
       [13.692396 ],
       [13.675688 ],
       [13.664442 ],
       [13.67144  ],
       [13.664776 ],
       [13.682194 ],
       [13.668834 ],
       [13.689348 ],
       [13.683475 ],
       [13.644897 ],
       [13.670074 ],
       [13.65994  ],
       [13.69416  ],
       [13.74135  ],
       [13.767466 ],
       [13.660621 ],
       [13.728923 ],
       [13.796329 ],
       [13.825548 ],
       [13.893202 ],
       [13.817729 ],
       [13.826949 ],
       [13.818247 ],
       [13.813678 ],
       [13.767135 ],
       [13.765775 ],
       [13.783654 ],
       [13.794539 ],
       [13.816212 ],
       [13.779476 ],
       [13.777074 ],
       [13.7972355],
       [13.738898 ],
       [13.777591 ],
       [13.789122 ],
       [13.720045 ],
       [13.720141 ],
       [13.696989 ],
       [13.717006 ],
       [13.768758 ],
       [13.781691 ],
       [13.793615 ],
       [13.79796  ],
       [13.836642 ],
       [13.76362  ],
       [13.817443 ],
       [13.777869 ],
       [13.739777 ],
       [13.740601 ],
       [13.786933 ],
       [13.754926 ],
       [13.693532 ],
       [13.717031 ],
       [13.71125  ],
       [13.740833 ],
       [13.703761 ],
       [13.703118 ],
       [13.661376 ],
       [13.658561 ],
       [13.644117 ],
       [13.682677 ],
       [13.703119 ],
       [13.673181 ],
       [13.683593 ],
       [13.67763  ],
       [13.724342 ],
       [13.731253 ],
       [13.751887 ],
       [13.750514 ],
       [13.724638 ],
       [13.810499 ],
       [13.729644 ],
       [13.734325 ],
       [13.780653 ],
       [13.777232 ],
       [13.769865 ],
       [13.72179  ],
       [13.780026 ],
       [13.712486 ],
       [13.674738 ],
       [13.708554 ],
       [13.77347  ],
       [13.744871 ],
       [13.71553  ],
       [13.711356 ],
       [13.734901 ],
       [13.703149 ],
       [13.6891165],
       [13.7157   ],
       [13.661826 ],
       [13.688608 ],
       [13.678672 ],
       [13.662362 ],
       [13.686739 ],
       [13.779556 ],
       [13.76245  ],
       [13.74391  ],
       [13.7521105],
       [13.716466 ],
       [13.736428 ],
       [13.757762 ],
       [13.737133 ],
       [13.7742815],
       [13.793631 ],
       [13.723597 ],
       [13.779973 ],
       [13.803608 ],
       [13.759901 ],
       [13.716657 ],
       [13.822853 ],
       [13.813291 ],
       [13.739788 ],
       [13.715524 ],
       [13.67227  ],
       [13.696338 ],
       [13.662568 ],
       [13.644774 ],
       [13.670093 ],
       [13.725323 ],
       [13.737113 ],
       [13.754041 ],
       [13.67134  ],
       [13.729828 ],
       [13.723602 ],
       [13.722975 ],
       [13.665212 ],
       [13.6428795],
       [13.695272 ],
       [13.6951275],
       [13.675454 ],
       [13.657582 ],
       [13.647799 ],
       [13.678125 ],
       [13.642386 ],
       [13.675905 ],
       [13.727459 ],
       [13.581391 ],
       [13.66125  ],
       [13.662468 ],
       [13.647877 ],
       [13.695508 ],
       [13.705812 ],
       [13.678632 ],
       [13.666708 ],
       [13.665374 ],
       [13.647676 ],
       [13.648658 ],
       [13.658588 ],
       [13.653288 ],
       [13.64754  ],
       [13.638043 ],
       [13.625977 ],
       [13.607017 ],
       [13.651923 ],
       [13.603746 ],
       [13.684979 ],
       [13.625375 ],
       [13.670131 ],
       [13.612504 ],
       [13.63852  ],
       [13.599368 ],
       [13.59733  ],
       [13.62214  ],
       [13.595839 ],
       [13.633596 ],
       [13.57745  ],
       [13.6072645],
       [13.550692 ],
       [13.573113 ],
       [13.612986 ],
       [13.610103 ],
       [13.589033 ],
       [13.580708 ],
       [13.607607 ],
       [13.604743 ],
       [13.600832 ],
       [13.569926 ],
       [13.597994 ],
       [13.57494  ],
       [13.631486 ],
       [13.625644 ],
       [13.593891 ],
       [13.620773 ],
       [13.597055 ],
       [13.612128 ],
       [13.61774  ],
       [13.570467 ],
       [13.599237 ],
       [13.632169 ],
       [13.625973 ],
       [13.59451  ],
       [13.627049 ],
       [13.604172 ],
       [13.629194 ],
       [13.5925865],
       [13.620671 ],
       [13.640677 ],
       [13.642215 ],
       [13.5926895],
       [13.5987625],
       [13.589885 ],
       [13.571287 ],
       [13.592005 ],
       [13.628786 ],
       [13.581723 ],
       [13.587592 ],
       [13.610055 ],
       [13.642007 ],
       [13.606943 ],
       [13.584595 ],
       [13.6144285],
       [13.619416 ],
       [13.624341 ],
       [13.603384 ],
       [13.658183 ],
       [13.645589 ],
       [13.627143 ],
       [13.634075 ],
       [13.669626 ],
       [13.657416 ],
       [13.6536665],
       [13.66643  ],
       [13.655177 ],
       [13.647832 ],
       [13.662673 ],
       [13.684705 ],
       [13.65854  ],
       [13.698503 ],
       [13.695105 ],
       [13.700007 ],
       [13.696446 ],
       [13.68008  ],
       [13.732906 ],
       [13.70017  ],
       [13.695029 ],
       [13.719829 ],
       [13.743578 ],
       [13.741887 ],
       [13.720041 ],
       [13.703952 ],
       [13.780605 ],
       [13.733137 ],
       [13.747661 ],
       [13.780913 ],
       [13.749164 ],
       [13.76516  ],
       [13.75766  ],
       [13.763836 ],
       [13.751488 ],
       [13.785726 ],
       [13.774561 ],
       [13.796358 ],
       [13.763799 ],
       [13.777028 ],
       [13.85933  ],
       [13.913806 ],
       [13.757303 ]], dtype=float32)

In [120]:
train_y.slice(start,batch_size).to_torch().to('cuda:0', dtype=torch.float).squeeze()

tensor([13.8400, 13.8500, 13.8600, 13.8600, 13.8800, 13.9200, 13.9300, 13.9000,
        13.8800, 13.9000, 13.8900, 13.8800, 13.8700, 13.8500, 13.9000, 13.9100,
        13.9300, 13.9500, 13.9600, 13.9800, 13.9800, 14.0200, 14.0300, 14.0200,
        13.9900, 14.0200, 14.0300, 14.0400, 14.0400, 14.0500, 14.0400, 14.0600,
        14.0300, 14.0100, 13.9900, 14.0100, 14.0100, 14.0000, 13.9800, 13.9900,
        13.9800, 14.0200, 14.0200, 14.0200, 14.0500, 14.0300, 14.0200, 14.0200,
        14.0200, 14.0200, 14.0300, 14.0200, 14.0100, 14.0500, 14.0700, 14.0700,
        14.0400, 14.0400, 14.0400, 14.0600, 14.0400, 14.0500, 14.0300, 14.0400,
        14.0400, 14.0100, 14.0000, 13.9700, 13.9600, 13.9500, 13.9700, 14.0000,
        14.0100, 14.0100, 14.0200, 14.0200, 14.0100, 14.0100, 14.0000, 14.0100,
        14.0100, 14.0300, 14.0000, 14.0100, 14.0100, 14.0000, 14.0200, 14.0200,
        14.0500, 14.0600, 14.0600, 14.0500, 14.0400, 14.0400, 14.0500, 14.0500,
        14.0500, 14.0600, 14.0700, 14.0700, 14.0600, 14.0700, 14.0600, 14.0600,
        14.0800, 14.0700, 14.0800, 14.0800, 14.0900, 14.0800, 14.0900, 14.1000,
        14.0600, 14.0700, 14.0700, 14.0900, 14.0800, 14.0800, 14.0900, 14.1000,
        14.1000, 14.1000, 14.1100, 14.1100, 14.1100, 14.1100, 14.1300, 14.1500],
       device='cuda:0')

In [134]:
train_X.height

4338